coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
